name: Build

on:
  push:
  pull_request_target:
    types: [labeled]

jobs: 
  build:
    name: Test
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build
        run: bash ./gradlew assembleDebug
      - name: Upload accrescent APK
        uses: actions/upload-artifact@v4
        with:
          name: app-accrescent-debug
          path: presentation/build/outputs/apk/accrescent/debug/presentation-accrescent-debug.apk
      - name: Upload fdroid APK
        uses: actions/upload-artifact@v4
        with:
          name: app-fdroid-debug
          path: presentation/build/outputs/apk/fdroid/debug/presentation-fdroid-debug.apk
      - name: Upload apkstore APK
        uses: actions/upload-artifact@v4
        with:
          name: app-apkstore-debug
          path: presentation/build/outputs/apk/apkstore/debug/presentation-apkstore-debug.apk
      - name: Upload lite APK
        uses: actions/upload-artifact@v4
        with:
          name: app-lite-debug
          path: presentation/build/outputs/apk/lite/debug/presentation-lite-debug.apk
      - name: Upload playstore APK
        uses: actions/upload-artifact@v4
        with:
          name: app-playstore-debug
          path: presentation/build/outputs/apk/playstore/debug/presentation-playstore-debug.apk
